spring.application.name=SpringBootRestApiProject2
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_dbpb
spring.datasource.username=root
spring.datasource.password=Samba333
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8088
spring.jpa.show-sql=true
